---
apiVersion: v1
data:
  my.cnf: |
    [mysqld]
    innodb_buffer_pool_size=2G
kind: ConfigMap
metadata:
  labels:
    app: mariadb-app
  name: mariadb-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mariadb-app
  name: mariadb-app
spec:
  template:
    metadata:
      labels:
        app: mariadb-app
    spec:
      containers:
      - env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: mariadb-app
        - name: MARIADB_USER
          value: ""
        - name: MARIADB_DATABASE
          value: ""
        image: bitnami/mariadb:10.1.26-r2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: mariadb
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /bitnami/mariadb/conf/my_custom.cnf
          name: config
          subPath: my.cnf
        - mountPath: /bitnami/mariadb
          name: data
      - command:
        - sh
        - -c
        - DATA_SOURCE_NAME="root:$MARIADB_ROOT_PASSWORD@(localhost:3306)/" /bin/mysqld_exporter
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-root-password
              name: mariadb-app
        image: prom/mysqld-exporter:v0.10.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        name: metrics
        ports:
        - containerPort: 9104
          name: metrics
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources: {}
      volumes:
      - configMap:
          name: mariadb-app
        name: config
      - name: data
        persistentVolumeClaim:
          claimName: mariadb-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mariadb-app
  name: mariadb-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
data:
  mariadb-password: Ym9vdHM=
  mariadb-root-password: YWxzb2Jvb3Rz
kind: Secret
metadata:
  labels:
    app: mariadb-app
  name: mariadb-app
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
  labels:
    app: mariadb-app
  name: mariadb-app
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  - name: metrics
    port: 9104
    targetPort: metrics
  selector:
    app: mariadb-app
  type: ClusterIP