---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: redis-app
  name: redis-app
spec:
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
      - env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-app
        image: bitnami/redis:3.2.9-r2
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: redis-app
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /bitnami/redis
          name: redis-data
      - env:
        - name: REDIS_ALIAS
          value: redis-app
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis-app
        image: oliver006/redis_exporter:v0.11
        imagePullPolicy: IfNotPresent
        name: metrics
        ports:
        - containerPort: 9121
          name: metrics
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-app
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: redis-app
  name: redis-app
spec:
  ingress:
  - ports:
    - port: 9121
  - from:
    - podSelector: null
    ports:
    - port: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis-app
  name: redis-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: '-'
---
apiVersion: v1
data:
  redis-password: Wm05dlltRnk=
kind: Secret
metadata:
  labels:
    app: redis-app
  name: redis-app
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9121"
    prometheus.io/scrape: "true"
  labels:
    app: redis-app
  name: redis-app
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis-app
