---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx-app
  name: nginx-app
spec:
  replicas: 1
  template:
    metadata
      labels:
        app: nginx-app
    spec:
      containers:
        - image: 'bitnami/nginx:1.10.2-r3'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
          name: nginx-app
          ports:
            - containerPort: 80
              name: http
            - containerPort: 443
              name: https
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /bitnami/nginx
              name: nginx-data
            - mountPath: /bitnami/nginx/conf/vhosts
              name: nginx-vhost
      volumes:
        - emptyDir: {}
          name: nginx-data
        - configMap:
            name: nginx-app
          name: nginx-vhost
---
apiVersion: v1
data:
  vhost.conf: |
    server {
      listen 0.0.0.0:80;
      root /app;
      location / {
        index index.html index.php;
      }
      location ~ \.php$ {
        fastcgi_pass phpfpm-server:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }
kind: ConfigMap
metadata:
  labels:
    app: nginx-app
  name: nginx-app
